package mvf314.mvflib.item;

import mvf314.mvflib.tools.ITranslatable;
import net.minecraft.item.Item;

import java.util.HashMap;
import java.util.Map;

/**
 * The BaseItem abstract class is a wrapper for the Item class and binds a registry name to the object.
 * @author Mvf314
 * @version 0.0.3
 * @since 0.0.1
 */
public abstract class BaseItem extends Item implements ITranslatable {

	/**
	 * Registry name of the item
	 */
	public final String NAME;

	/**
	 * Language map
	 */
	protected Map<String, String> lang = new HashMap<>();

	/**
	 * Construct an Item object with the given properties. These can be generated by an {@link ItemPropertyProvider}.
	 * @param prop  Properties of the item
	 * @param name  Registry name of the item
	 */
	public BaseItem(Item.Properties prop, String name) {
		super(prop);
		NAME = name;
		setRegistryName(name);
	}

	/**
	 * Get the language map
	 * @return Language map
	 */
	public Map<String, String> getLang() {
		return lang;
	}
}
