package mvf314.mvflib.item;

import net.minecraft.item.Item;

/**
 * The BaseItem abstract class is a wrapper for the Item class and binds a registry name to the object.
 * @author Mvf314
 * @version 0.0.2
 */
public abstract class BaseItem extends Item {

	/**
	 * Registry name of the item
	 */
	public final String NAME;

	/**
	 * Construct an Item object with the given properties. These can be generated by an {@link ItemPropertyProvider}.
	 * @param prop  Properties of the item
	 * @param name  Registry name of the item
	 */
	public BaseItem(Item.Properties prop, String name) {
		super(prop);
		NAME = name;
		setRegistryName(name);
	}
}
